### ISSUE TITLE
Don't add links in pubspec when app depends on dart:io

### ISSUE THREAD

**Issue by Sfshaza** [kasperpeulen/gist-generator#10]
As it says, when a file depends on dart:io, please do not add the gist and dartpad links to the pubspec.

**Comment by kasperpeulen** [comment]
@Sfshaza I can not reproduce this one, also this file that should test this behaviour, seems to pass for me:
https://github.com/kasperpeulen/gist-generator/blob/master/test/dartpadable_test.dart

**Comment by Sfshaza** [comment]
I spent some time on this. Note to self: next time include specific details. I can't reproduce it or remember which pubspec was being erroneously updated. I'm closing this one.
