### ISSUE TITLE
Please document args

### ISSUE THREAD

**Issue by Sfshaza** [kasperpeulen/gist-generator#12]
Hey!

I want to test some of the bugs I filed earlier that you can't reproduce. I want to use the facility you added to create test gists files, but the --help option doesn't document it. (I believe it's --dry-run --verbose.) Any other args that can be added to the help file?

thx!

**Comment by kasperpeulen** [comment]
@Sfshaza 

This is how help looks to me:

```
$ gist generate --help
Generate gists from the current directory.

Usage: gist generate [directory]
-h, --help         Print this usage information.
-v, --verbose      Show extra information about why a directory is skipped.
-n, --dry-run      Show which directories would be converted to gists.
-t, --test-gist    Create anonymous test gist, instead of creating public gists.

Run "gist help" to see global options.
```

```
$ gist --help
Gist manager.

Usage: gist <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  generate   Generate gists from the current directory.
  help       Display help information for gist.

Run "gist help <command>" for more information about a command.
```

**Comment by Sfshaza** [comment]
Hmmm... Strange. This is what I see.

---

gist-generator [master] $ pwd
/Users/shaza/TMP-gist-generator/gist-generator
gist-generator [master] $ git pull
Already up-to-date.
gist-generator [master] $ dart bin/gist.dart --help
Gist manager.

Usage: gist <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  generate   Generate gists from the current directory.
  help       Display help information for gist.

Run "gist help <command>" for more information about a command.

**Comment by kasperpeulen** [comment]
Hmm ... that is strange...

I do this:

`$ pub global activate --source git https://github.com/kasperpeulen/gist-generator`
`$ gist generate --help`

but I wouldn't think that could make a difference.

**Comment by kasperpeulen** [comment]
oh wait you do `gist --help` I think `gist generate --help` will give the information @Sfshaza

**Comment by Sfshaza** [comment]
Yup! I thought I had tried that yesterday but that does work. Closing!
