### ISSUE TITLE
Support generating a gist from the app's root directory

### ISSUE THREAD

**Issue by kwalrath** [kasperpeulen/gist-generator#2]
Adding an issue to track the suggestion I made in #1.

Although it's wonderful to be able to generate multiple gists at once, sometimes you're not ready to update them all. Or maybe the repo only has one app in it. Being able to run `generate gist` from the app's root directory, rather than the parent of that directory, would be nice. It'd be fine to add a command-line option to either one, if necessary.

**Comment by kasperpeulen** [comment]
I see at @kwalrath. Will try to implement that. Not sure what you mean with the command line option ?

Maybe make two command `gist generate` and `gist generate_all` or something like that ?

**Comment by kasperpeulen** [comment]
@kwalrath 

It now works like this:
It first checks if there is pubspec.yaml file in the root of the directory. If so, it tries to make a gist of the root. Otherwise, it will try to make a gist of every directory in the project.

**Comment by kwalrath** [comment]
:+1:

**Comment by kwalrath** [comment]
I just tried it, and it works for me. Thanks!
