### ISSUE TITLE
Don't overwrite existing gists until we test the new version

### ISSUE THREAD

**Issue by kwalrath** [kasperpeulen/gist-generator#8]
This isn't an issue yet, but in the future when we're replacing existing gists, we'll want to be able to make sure those gists work well in DartPad before we replace the existing gist. Possible issues are failure to execute, code that's too wide, DartPad section sizes that need adjustment (for particularly large or small output, for example), ...

It would be nice if there were a command-line option for either "yes, replace my gist" or "just testing, don't replace the gist". It could be something like `--replace` / `-r` or `--test-gist` / `-t`.

@Sfshaza do you have any preference? Anything to add?

**Comment by kasperpeulen** [comment]
so maybe make an anonymous or secret gist, for the testing ? @kwalrath

**Comment by kwalrath** [comment]
Secret might be good, just so we know that it's not one we intend to publish.

**Comment by kasperpeulen** [comment]
I'm thinking, if you are going to do this for a long time, and create everytime a new gist when testing, you may end up with hundreds of gists here:
https://gist.github.com/kwalrath

maybe secret + anonymous ?

**Comment by kwalrath** [comment]
Sure, that sounds good. I haven't used secret + anonymous, but as long as I don't lose the window that says where the gists are... it should be good. I can always regenerate if I do lose it.

**Comment by kasperpeulen** [comment]
this should be fixed now

**Comment by kwalrath** [comment]
It works great. Thanks!
