### ISSUE TITLE
Suggestions for pubspec.yaml

### ISSUE THREAD

**Issue by kwalrath** [kasperpeulen/gist-generator#9]
This can wait until later, but...

It would be nice to advertise the dartpad corresponding to each generated gist. Also, I'm not sure that "homepage" is the right word for where the gist is. For dart tutorial samples, the real homepage is either the dart-tutorial-samples repo or (probably better) the doc page with the embedded dartpad.

If we created custom fields for the gist and dartpad locations, would anything bad happen? I'm thinking instead of this:

```
homepage: http://gist.github.com/kwalrath/a0d6042d97b7e71347c2
```

Have this:

```
gist: http://gist.github.com/kwalrath/a0d6042d97b7e71347c2
dartpad: https://dartpad.dartlang.org/a0d6042d97b7e71347c2
```

It might not be a bad idea for us to add a homepage entry (by hand):

```
homepage: https://www.dartlang.org/docs/dart-up-and-running/ch02.html
gist: http://gist.github.com/kwalrath/a0d6042d97b7e71347c2
dartpad: https://dartpad.dartlang.org/a0d6042d97b7e71347c2
```

What do you think?

/cc @sfshaza

**Comment by kasperpeulen** [comment]
sounds good to me, should work now like that

**Comment by kwalrath** [comment]
Cool. Thanks!!
